# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LCMp68uaNMV-oX-Xf9PRMbdkVt9e_7DK

# Matplotlib

**bar chart**
"""

import matplotlib.pyplot as plt
x=["part1","part2","part3","part4",'part5']
y=[98,67,88,95,88]
plt.xlabel("parts of herry potter")
plt.ylabel("populatity",fontsize=18)
color=["red","green","yellow","blue","orange"]
plt.title("Populatity of herry potter",fontsize=22)
plt.bar(x,y,color=color,edgecolor="black"   )
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_excel("expense3.xlsx")
print(df)

print(df.info() )

print(df.isnull().sum())
df['Payment Mode']=df['Payment Mode'].fillna(df['Payment Mode'].mode()[0])
print(df.isnull().sum())

plt.bar(df['Payment Mode'], df['Amount'])
plt.show()
grouped_by=df.groupby('Payment Mode')["Amount"].sum()
print(grouped_by)
print(df.groupby('Payment Mode').agg({'Amount':sum}))
plt.bar(grouped_by.index,grouped_by.values)
plt.show()

"""**line plot**"""

# line plot

import matplotlib.pyplot as plt
x=["day1",'day2','day3','day4','day5']
y=[300,200,240,390,340]
y1=[400,300,200,340,290]
# plt.plot(x,y,marker="^")
# plt.plot(x,y,marker="o")
plt.plot(x,y,marker="D",ls="--",color="red",label="Week1")
plt.plot(x,y1,marker="^",ls="-",color="green",label="week2",alpha=0.5)
plt.legend()
plt.show()

import pandas as pd
df=pd.read_excel("expense3.xlsx")
print(df)

print(df.info())

print(df.isnull().sum())
df['Payment Mode']=df['Payment Mode'].fillna(df['Payment Mode'].mode()[0])
print(df.isnull().sum())

# plt.plot(df['Date'],df['Amount'])
grouped_by = df.groupby("Category")["Amount"].sum()
print(grouped_by)

plt.figure(figsize=(10,6))  # optional, bigger figure
plt.plot(range(len(grouped_by)), grouped_by.values, marker='o')  # numeric x-axis
plt.xticks(ticks=range(len(grouped_by)), labels=grouped_by.index, rotation=45)  # set labels manually
plt.xlabel('Category')
plt.ylabel('Total Amount')
plt.title('Line Chart: Total Amount by Category')
plt.grid(True)
plt.show()

"""**scatter plot**"""

# scatter plot
import matplotlib.pyplot as plt
import numpy as np
x=np.random.randint(1,10,50)
y=np.random.randint(10,100,50)
color=np.random.randint(1,10,50)
# scatter plot
import matplotlib.pyplot as plt
import numpy as np
x=np.random.randint(1,10,50)
y=np.random.randint(10,100,50)
color=np.random.randint(1,10,50)
print(x)
print(y)
plt.scatter(x,y,marker="o",cmap="viridis",c=color) # corrected cmap and c
plt.colorbar()
plt.show()

color=np.random.randint(1,100,50)
size=np.random.randint(1,100,50)
plt.scatter(x,y,marker="*",cmap="hot",c=color,s=size) # corrected cmap and c
plt.colorbar()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
df=pd.read_excel("ESD.xlsx")
print(df)

print(df.isnull().sum())

color=np.random.randint(1,100,50)
size=np.random.randint(1,100,50)
plt.scatter(df['EEID'],df['Age'],marker="*")
plt.show()
# when we have numerical numerical value

"""**pie chart**"""

# pie chart
import matplotlib.pyplot as plt
brands=["oneplus","vivo","apple","nokia","redmi"]
x=[27,35,50,22,33]
c=["red","green","pink","blue","orange"]
ex=[0,0,0,0,1]
plt.pie(x,labels=brands,autopct="%1.2f%%",colors=c,explode=ex,shadow=True,startangle=180)
plt.show()

import pandas as pd
data=pd.read_excel("expense3.xlsx")
print(data)

print(data.isnull().sum())
data['Payment Mode']=data['Payment Mode'].fillna(data['Payment Mode'].mode()[0])
print(data.isnull().sum())

plt.pie(data['Amount'])
plt.show()

group_by=data.groupby('Payment Mode')["Amount"].sum()
print(group_by)
plt.pie(group_by.values,labels=group_by.index,autopct="%1.2f%%",shadow=True,colors=c)
plt.show()

"""**box plot**"""

import matplotlib.pyplot as plt
l=[40,46,45,46,45,44,43,44,42,47,55,56,59,66,66,56,65,67,68,67,65]
plt.boxplot(l)
plt.show()

x=[1,3,4,7,12,8,9,24]
plt.boxplot(x)
plt.show()

x=[1,3,4,7,12,8,9,24]
y=[2,3,4,5,6,7,7,5,4,3,10]
plt.boxplot([x,y])
plt.show()

plt.show()

print(data)

plt.boxplot(data['Amount'])
plt.show()

"""**Histogram plot**"""

import matplotlib.pyplot as plt
x=[20,30,40,50,30,2,22,33,40,2,30,4,50,43,2,23,23]
plt.hist(x,bins=25,edgecolor="black",color="pink")
plt.show()

import pandas as pd
df=pd.read_excel("ESD.xlsx")
print((df))

plt.hist(df['Age'],bins=25,edgecolor="black",color="pink")

"""**Violin plot**"""

import matplotlib.pyplot as plt
a=[20,30,20,40,34,2,23,24,20,30,34,35,32,34,23,23]

plt.violinplot(a,showmedians=True)
plt.show()

print(df)

plt.violinplot(df['Age'],showmedians=True)
plt.show()

plt.violinplot(df['Annual Salary'],showmedians=True)
plt.show()

"""**stem plot**"""

import matplotlib.pyplot as plt
x=[10,20,30,20,40,30,50,30,44,22,13,24,34]
plt.stem(x)
plt.show()

import matplotlib.pyplot as plt
x=[10,20,30,20,40,30,50,30,44,22,13,24,34]
plt.stem(x,linefmt="--",markerfmt="D",bottom=10,
         orientation="horizontal")
plt.show()

print(df) # ESD.xlsx

# pr employee
df2=df.head(20)
plt.stem(df2['Age'],linefmt="--",
       )
plt.plot(df2["Age"])
plt.show()

"""**stack plot**"""

import matplotlib.pyplot as plt
days=[1,2,3,4,5,6,7]
NOP=[5,10,12,20,35,40,50]
NOP2=[10,2,30,25,40,50,90]
NOP3=[8,12,17,22,34,30,44]
plt.stackplot(days,NOP,NOP2,NOP3,labels=["week1","week2","week3"],colors=["pink","hotpink","magenta"])
plt.legend()
plt.show()

import pandas as pd
df=pd.read_csv("food_data.csv")
print(df)

print(df.isnull().sum())

df['Carbs']=df['Carbs'].fillna(df['Carbs'].mean())
df['Protein']=df['Protein'].fillna(df['Calories'].mean())
df['Fibre']=df['Fibre'].fillna(df['Fibre'].mean())
df['Fat']=df['Fat'].fillna(df['Fat'].mean())
print(df.isnull().sum())

plt.stackplot(df['Calories'],df['Fibre'])
plt.show()

"""**step plot**"""

import matplotlib.pyplot as plt
x=["day1","day2","day3","day4","day5"]
y=[300,200,240,390,340]
plt.step(x,y,where="post") # mid
plt.show()

import pandas as pd
df=pd.read_excel("expense3.xlsx")
print(df)
print(df.isnull().sum())
df['Payment Mode']=df['Payment Mode'].fillna(df['Payment Mode'].mode()[0])
print(df.isnull().sum())

group=df.groupby("Category").agg({"Amount":"sum"})
print(group)

grouped_by = df.groupby("Category")["Amount"].sum()

plt.figure(figsize=(10,6))
plt.step(range(len(grouped_by)), grouped_by.values, where="mid", marker="o")
plt.xticks(ticks=range(len(grouped_by)), labels=grouped_by.index, rotation=45)
plt.xlabel('Category')
plt.ylabel('Total Amount')
plt.title('Step Chart: Total Amount by Category')
plt.grid(True)
plt.show()

"""**legend**"""

import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[45,67,33,67,12,]
y1=[41,60,13,66,13]
y2=[45,67,42,63,12,]
plt.figure(figsize=[5,3])
plt.plot(x,y,label="line1")
plt.plot(x,y1,label="line2")
plt.plot(x,y2,label="line3")
plt.legend(["male","female","other"],bbox_to_anchor=(0.8,1.1),ncols=2 ,labelspacing=2)
plt.show()
# ncols no of colums in legend
# 10 for center


plt.show()

"""**sub plot**"""

import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[23,24,34,34,56]
plt.subplot(2,3,1)
plt.plot(x,y)
x=[6,7,8,9,10]
y=[34,45,67,89,87]
plt.subplot(2,3,2)
plt.plot(x,y)
x=[6,7,8,2,1]
y=[32,34,56,78,86]
plt.subplot(2,3,3)
plt.plot(x,y)
plt.show()

x=[1,2,3,4,5]
y=[23,24,34,34,56]
plt.subplot(2,3,1)
plt.plot(x,y)
x=[6,7,8,9,10]
y=[34,45,67,89,87]
plt.subplot(2,3,2)
plt.plot(x,y)
x=[6,7,8,2,1]
y=[32,34,56,78,86]
plt.subplot(2,2,3)
plt.plot(x,y)
x=[6,7,8,2,1]
y=[32,34,56,78,86]
plt.subplot(2,2,4)
plt.plot(x,y)
plt.show()

x=[1,2,3,4,5]
y=[23,24,34,34,56]
plt.title("age")
plt.subplot(2,2,1)
plt.plot(x,y)
x=[6,7,8,9,10]
y=[34,45,67,89,87]
plt.title("salary")
plt.subplot(2,2,2)
plt.bar(x,y)
plt.suptitle("employee")
plt.show()

"""**how to save it**"""

import matplotlib.pyplot as plt
x=["part1","part2","part3","part4",'part5']
y=[98,67,88,95,88]
plt.xlabel("parts of herry potter")
plt.ylabel("populatity",fontsize=18)
color=["red","green","yellow","blue","orange"]
plt.title("Populatity of herry potter",fontsize=22)
plt.bar(x,y,color=color,edgecolor="black"   )
plt.savefig("plot.png")
plt.show()

# pie chart
import matplotlib.pyplot as plt
brands=["oneplus","vivo","apple","nokia","redmi"]
x=[27,35,50,22,33]
c=["red","green","pink","blue","orange"]
ex=[0,0,0,0,1]
plt.pie(x,labels=brands,autopct="%1.2f%%",colors=c,explode=ex,shadow=True,startangle=180)
plt.savefig("pie.png",facecolor="black")
plt.show()