# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ol3PlASLm6Lx4-v8RoNVPw8cCFL-fPNE

# Pandas
"""

import pandas as pd
data={"name":["jon","Peter","Lisa"],
      "Age":[25,28,31],
      "Salary":[300000,45000,25000]}
df=pd.DataFrame(data)
print(df)

df=pd.read_excel("expense3.xlsx")
print(df)

print(df.head())

print(df.tail(10))

print(df.info())

print(df.describe())

print(df.isnull().sum())

"""**handling Duplicate values and missinging values**"""

# handling Duplicate values
data=pd.read_csv("company1.csv")
print(data)

print(data.info())

print(data.describe())

print(data.isnull().sum())

print(data["EEID"].duplicated().sum())

print(data.drop_duplicates("EEID"))

# missinging values in it
print(data.isnull().sum())

print(data.dropna()) # can't drop

print(data)

import numpy as np
print(data.replace(np.nan,30000))

data["salary"]=data["salary"].replace(np.nan,30000)
print(data)

print(data)

data["salary"]=data["salary"].replace(np.nan,data["salary"].mean())
print(data)
print(data["salary"].mean())

print(data)

"""backward and forward fill"""

print(data.fillna(method="bfill")) # back word fill

print(data.fillna(method="ffill")) # forword fill

"""**columns Transformation**"""

import pandas as pd
df=pd.read_excel("ESD.xlsx")
print(df)

df.loc[(df["Bonus %"]==0),"GetBonus"]="no bouns"
df.loc[(df['Bonus %']>0),"GetBonus"]="bonus"
print(df)

import pandas as pd
df=pd.read_csv("company1.csv")
print(df)

df["salary"]=df["salary"].replace(np.nan,df["salary"].mean())
print(df)

df["Name"]=df["Name"].fillna  (method="ffill")
df["gender"]=df["gender"].fillna(method="ffill")
print(df)

df["Bonus"]=(df["salary"]/100)*20
print(df)

import pandas as pd
data={"Months":["January","February","March","April"]}
a=pd.DataFrame(data)
print(a)

def extract(value):
  return value[:3]
a["Short_months"]=a["Months"].map(extract)
print(a)

"""**group by in pandas**"""

import pandas as pd
data=pd.read_excel("ESD.xlsx")
print(data.head())

gp=data.groupby("Department").agg({"Gender":"count"})
print(gp)

gp=data.groupby(["Department","Gender"]).agg({"EEID":"count"})
print(gp)

gp1=data.groupby(["Country","Gender"]).agg({"Age":"mean","Annual Salary":"max"})
print(gp1)

"""**Merge join concatenate in pandas**"""

import pandas as pd
data1={"Emp ID":["E01","E02","E03","E04","E05","E06"],
       "Employee":["jon","ken","ravi","herry","jerry","killva"],
       "Age":[22,23,24,26,28,21]}
data2={"Emp ID":["E01","E02","E03","E04","E05","E06"],
       "Salary":[20000,30000,32000,21000,33000,19000]}
data=pd.DataFrame(data1)

data1=pd.DataFrame(data2)
print(data)
print()
print(data1)

print(pd.merge(data,data1,on="Emp ID"))

import pandas as pd
data1={"Emp ID":["E01","E02","E03","E04","E09","E06"],
       "Employee":["jon","ken","ravi","herry","jerry","killva"],
       "Age":[22,23,24,26,28,21]}
data2={"Emp ID":["E01","E07","E03","E04","E05","E06"],
       "Salary":[20000,30000,32000,21000,33000,19000]}
data=pd.DataFrame(data1)

data1=pd.DataFrame(data2)
print(data)
print()
print(data1)

print(pd.merge(data,data1,on="Emp ID"))

print(pd.merge(left=data,right=data1,on="Emp ID",how="left"))

print(pd.merge(left=data,right=data1,on="Emp ID",how="right"))

data1={"Emp ID":["E01","E02","E03","E04","E09","E06"],
       "Employee":["jon","ken","ravi","herry","jerry","killva"],
       "Age":[22,23,24,26,28,21]}
data2={"Emp ID":["E07","E08","E09","E10","E11","E12"],
       "Employee":["jan","keen","radi","hero","jemel","jin wo sung"],
       "Age":[22,23,24,26,28,21]}
data1=pd.DataFrame(data1)
data2=pd.DataFrame(data2)
print(data1)
print()
print(data2)

print(pd.concat([data1,data2]))

"""**compare dataframe**"""

import pandas as pd
dict={"Fruits":["mango","banana","papaya","apple"],
      "Price":[100,80,150,210],
      "Quatity":[15,10,10,3]}
df1=pd.DataFrame(dict)
print(df1)

df2=df1.copy()
df2.loc[0,"Price"]=120
df2.loc[1,"Quatity"]=12
df2.loc[2,"Fruits"]="kiwi"
df2.loc[2,"Price"]=120
df2.loc[3,"Quatity"]=12

print(df2)

print(df.compare(df2))
print()
print(df1.compare(df2,keep_equal=True))
print()
print(df1.compare(df2,keep_shape=True))
print()
print(df1.compare(df2,keep_shape=True,keep_equal=True))

"""**pivoting and melting**"""

# pivoting
import pandas as pd
dict={"keys":["k1","k2","k1","k2"],
      "Name":["jon","peter","ben","gojo"],
      "Houses":["red","blue","green","red"],
      "Grades":["3rd",'4th',"5th","3rd"]}
df=pd.DataFrame(dict)
print(df)

print(df.pivot(index="keys",columns="Name",values=["Houses","Grades"]))

# melting
dict={
      "Name":["jon","peter","ben","gojo"],
      "Houses":["red","blue","green","red"],
      "Grades":["3rd",'4th',"5th","3rd"]}
df=pd.DataFrame(dict)
print(df)

print(pd.melt(df,id_vars=["Name"],value_vars=["Houses","Grades"]))

print(pd.melt(df,id_vars=["Name"],value_vars=["Houses","Grades"],value_name="values_of Houses",var_name="names"))