# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plB360gOUr5FpL7P3CAKtFqXM4H6zFqC

# Seaborn

**line plot**
"""

import seaborn as sns
import pandas as pd
data={"Days":[1,2,3,4,5,6,7],
      "NOP":[1000,1200,1300,1400,1500,1600,1700]}
df=pd.DataFrame(data)
print(df)

import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))

sns.lineplot(x="Days",y="NOP",data=df)
plt.show()

df=pd.read_excel("ESD.xlsx")
print(df)

sns.lineplot(data=df,x="Business Unit",y="Age",hue="Gender"
,style="Ethnicity")

color=sns.color_palette("GnBu")
sns.lineplot(data=df,x="Business Unit",y="Age",hue="Ethnicity",
             palette=color
)

"""**bar plot**"""

import seaborn as sns
import matplotlib.pyplot as plt
data=sns.load_dataset("tips")
print(data)

sns.barplot(data=data,x="day",y="tip",hue="sex")

from platform import platform
plt.figure(figsize=(3,3))
sns.barplot(data=data,x="day",y="tip",hue="sex",estimator="median" ,palette="spring",
            order=["Sun","Sat","Fri","Thur"],
            errorbar=("ci",0))
plt.show()

"""**histogram plot**"""

import seaborn as sns
import matplotlib.pyplot as plt
data=sns.load_dataset("tips")
print(data)

sns.histplot(data=data,x="day",hue="sex",kde=True)

data=sns.load_dataset("titanic")

sns.histplot(data=data,x="age",hue="who",kde=True)
# look frequency of data

data=sns.load_dataset("titanic")

sns.histplot(data=data,x="age",hue="who",kde=True,bins=30)

"""**scatter plot**"""

# for number to number data

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
data=sns.load_dataset("tips")
print(data)

sns.scatterplot(data=data,x="total_bill",y="tip",hue="sex",style="smoker")

sns.scatterplot(data=data,x="total_bill",y="tip",hue="day",style="size")

data=pd.read_excel("ESD.xlsx")
print(data)

sns.scatterplot(data=data,x="Age",y="Annual Salary",size="Bonus %",hue="Department")
plt.legend(bbox_to_anchor=(1.05,1)) # ( x axis, y axis, width ,height )
plt.show()

"""**heatmap**"""

# use for number to number value
import matplotlib.pyplot as plt
import seaborn as sns
data=sns.load_dataset("tips")
print(data)

import seaborn as sns
import matplotlib.pyplot as plt

# Load example dataset
tips = sns.load_dataset("tips")

# Create a pivot table: average total_bill per day and sex
heatmap_data = tips.pivot_table(index="day", columns="sex", values="total_bill", aggfunc="mean")

# Plot heatmap
sns.heatmap(data=heatmap_data, cmap="YlGnBu", annot=True)
plt.title("Average Total Bill by Day and Sex")
plt.show()

import pandas as pd
data=pd.read_excel("ESD.xlsx")
print(data)

groupby=data.groupby("Job Title").agg({"Annual Salary":"mean"})
print(groupby)

sns.heatmap(groupby)

"""**count plot**"""

import seaborn as sns
import matplotlib.pyplot as plt

data=sns.load_dataset("tips")
print(data)

sns.countplot(data=data,x="day")

df=pd.read_excel("ESD.xlsx")
print(df)

sns.countplot(data=df,x="Department",hue="Gender",palette="GnBu")

"""**violin plot**"""

import matplotlib.pyplot as plt
import seaborn as sns
data=sns.load_dataset("tips")
print(data)

sns.violinplot(data=data,x="day",y="total_bill",hue="sex")

df=pd.read_excel("ESD.xlsx")
print(df)

sns.violinplot(data=df,x="Bonus %",)

"""**pair plot**"""

# pairs of different plot --- numerical numerical type data
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
df=sns.load_dataset('tips')
df.head()
sns.pairplot(df)
plt.show()

sns.pairplot(df,hue='sex',diag_kind="hist")

df=sns.load_dataset("iris")

sns.pairplot(df,hue="species")

"""**strip plot**"""

data=sns.load_dataset("tips")
sns.stripplot(data=data,x="day",y="total_bill" ,hue="sex",dodge=True,
              jitter=0.1)

sns.scatterplot(data=data,x="day",y="total_bill")

"""**box plot**"""

import matplotlib.pyplot as plt
import seaborn as sns
data=sns.load_dataset("tips")
print(data)

sns.boxplot(data=data,x="tip")

sns.boxplot(data=data,x="day",y="tip",hue="sex")

"""**cat plot**"""

# categorical plot
import matplotlib.pyplot as plt
import seaborn as sns
data=sns.load_dataset("tips")
print(data)

sns.catplot(data=data,x="day",y="tip",hue="sex",kind="bar")

sns.catplot(data=data,x="day",y="tip",hue="sex",kind="violin")

"""**style and color**"""

import matplotlib.pyplot as plt
import seaborn as sns
data=sns.load_dataset("exercise")
print(data)

sns.barplot(data=data,x="time",y="pulse",palette="GnBu")

sns.set_style(style="ticks")

sns.barplot(data=data,x="time",y="pulse",palette="GnBu")

sns.palplot(sns.color_palette("GnBu"))

sns.palplot(sns.color_palette())

sns.palplot(sns.color_palette("viridis"))

sns.palplot(sns.color_palette("Paired"))

sns.palplot(sns.color_palette("spring",2))

"""**multiple plots**"""

import matplotlib.pyplot as plt
import seaborn as sns
data=sns.load_dataset("tips")
print(data)

a=sns.FacetGrid(data,col="day",height=2)
a.map(sns.scatterplot,"total_bill","tip")
plt.show()

a=sns.FacetGrid(data,col="time",height=2,hue="sex")
a.map(sns.barplot,"day","tip")
plt.show()

"""**relational plot**"""

import seaborn as sns
import matplotlib.pyplot as plt
data=sns.load_dataset("tips")
print(data)

sns.relplot(data=data,x="total_bill",y="tip",hue="sex",style="smoker",col="day")

"""**swar plot**"""

import seaborn as sns
import matplotlib.pyplot as plt
data=sns.load_dataset("tips")
print(data)

sns.swarmplot(data=data,x="day",y="total_bill",hue="sex",dodge=True) # no overlaping of data

sns.stripplot(data=data,x="day",y="total_bill",hue="sex",dodge=True)

"""**KDE plot**"""

# kenal density essitimation
import seaborn as sns
import matplotlib.pyplot as plt
data=sns.load_dataset("tips")
print(data)

sns.kdeplot(data=data,x="total_bill",hue="sex")

sns.histplot(data=data,x="total_bill",hue="sex")

sns.kdeplot(data=data,x="total_bill",hue="day",multiple="stack")

sns.kdeplot(data=data,x="total_bill",hue="day",multiple="fill")